[project]
name = "ku-nlp-group-25-project"
version = "1.0.0"
description = "NLP Group 25 Project"
readme = "README.md"
authors = [
    { name = "Haoyang Sun" },
    { name = "Kieran O'Neill", email = "zcd890@alumni.ku.dk" },
    { name = "Sultan Parvez" }
]
requires-python = ">=3.14"
dependencies = [
    "datasets>=5.0.1",
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
